//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Input/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""PlayerTiltLabyrinth"",
            ""id"": ""0e3ea27c-4d32-42b2-96af-545ea60d2771"",
            ""actions"": [
                {
                    ""name"": ""TiltLabyrinth"",
                    ""type"": ""Value"",
                    ""id"": ""1617b791-fb63-42da-926f-0d93c6947967"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5e1c639b-b715-435c-a955-6e1801f57225"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TiltLabyrinth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerTiltLabyrinth
        m_PlayerTiltLabyrinth = asset.FindActionMap("PlayerTiltLabyrinth", throwIfNotFound: true);
        m_PlayerTiltLabyrinth_TiltLabyrinth = m_PlayerTiltLabyrinth.FindAction("TiltLabyrinth", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerTiltLabyrinth
    private readonly InputActionMap m_PlayerTiltLabyrinth;
    private List<IPlayerTiltLabyrinthActions> m_PlayerTiltLabyrinthActionsCallbackInterfaces = new List<IPlayerTiltLabyrinthActions>();
    private readonly InputAction m_PlayerTiltLabyrinth_TiltLabyrinth;
    public struct PlayerTiltLabyrinthActions
    {
        private @PlayerInputs m_Wrapper;
        public PlayerTiltLabyrinthActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @TiltLabyrinth => m_Wrapper.m_PlayerTiltLabyrinth_TiltLabyrinth;
        public InputActionMap Get() { return m_Wrapper.m_PlayerTiltLabyrinth; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerTiltLabyrinthActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerTiltLabyrinthActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerTiltLabyrinthActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerTiltLabyrinthActionsCallbackInterfaces.Add(instance);
            @TiltLabyrinth.started += instance.OnTiltLabyrinth;
            @TiltLabyrinth.performed += instance.OnTiltLabyrinth;
            @TiltLabyrinth.canceled += instance.OnTiltLabyrinth;
        }

        private void UnregisterCallbacks(IPlayerTiltLabyrinthActions instance)
        {
            @TiltLabyrinth.started -= instance.OnTiltLabyrinth;
            @TiltLabyrinth.performed -= instance.OnTiltLabyrinth;
            @TiltLabyrinth.canceled -= instance.OnTiltLabyrinth;
        }

        public void RemoveCallbacks(IPlayerTiltLabyrinthActions instance)
        {
            if (m_Wrapper.m_PlayerTiltLabyrinthActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerTiltLabyrinthActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerTiltLabyrinthActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerTiltLabyrinthActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerTiltLabyrinthActions @PlayerTiltLabyrinth => new PlayerTiltLabyrinthActions(this);
    public interface IPlayerTiltLabyrinthActions
    {
        void OnTiltLabyrinth(InputAction.CallbackContext context);
    }
}
